### ISSUE TITLE
Ewi not detected ... 

### ISSUE THREAD

**Issue by Cziely93** [ledhed2222/EWItool#19]
Im trying to use EWItool with my 4000s , but even though my ports from my Roland um one mk2 are correctly set, it says "Ewi: not detected" at the bottom. 
Any help? Im out of answers :D

**Comment by ledhed2222** [comment]
Hey I'm just seeing this. What OS are you on? Please give any details possible.

**Comment by ledhed2222** [comment]
I think you guys have not connected your ewi correctly. I just tested this myself on Monterrey and it's fine. Please try to swap MIDI connections on your EWI, note that some USB -> MIDI cables are labeled backwards. That is to say that the "MIDI OUT" on the cable should be connected to the "MIDI IN" on the EWI, etc. 

If that doesn't work, please make a video showing what you're doing and upload it here for me to see.

**Comment by goshwinkle** [comment]
I think that's solved it. At least it's working on the PC now. Will try on
the Mac later and update.

**Comment by ledhed2222** [comment]
@goshwinkle how are you running this on PC? I've wanted to post a release of this for PC but don't have one at my disposal to make the cut. Are you compiling yourself?

**Comment by goshwinkle** [comment]
I didn't compile myself, I think it's the older Java version on the PC.
Newer one on Mac. Sorry for confusion.
